name: riverpod_issue
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.5
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
